version: '3'
services:
  db:
    image: 'postgres:9.6'
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - ./dockerfiles/postgresql.conf:/etc/postgresql.conf
    ports:
      - 127.0.0.1:5434:5432
    command: postgres -c config_file=/etc/postgresql.conf

  datachile-mondrian:
    image: 'datachile-mondrian:latest'
    environment:
      - APP_HOME=/datachile/
      - MONDRIAN_REST_CONF=/datachile-mondrian.yaml
      - VIRTUAL_HOST=chilecube.datawheel.us
      - LETSENCRYPT_HOST=chilecube.datawheel.us
      - LETSENCRYPT_EMAIL=datachile@datawheel.us
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./dockerfiles/datachile-mondrian.yaml:/datachile-mondrian.yaml
      - /home/manuel/datachile-mondrian/schema.xml:/mondrian-rest/schema.xml:ro
    ports:
      - 127.0.0.1:9393:9292

  datachile-canon:
    build:
      context: .
      dockerfile: dockerfiles/datachile-canon.dockerfile
    command: /bin/bash -c 'cp -R /datachile/static/* /datachile/static-shared/ && npm run start'
    environment:
      - NODE_ENV=production
      - CANON_PORT=4444
      - ROOT=/datachile
      - CANON_CONST_API=https://chilecube.datawheel.us/
      - CANON_GOOGLE_ANALYTICS=UA-109603240-1
      - CANON_LANGUAGES=es
      - CANON_LANGUAGES_DEFAULT=en
      - APP_HOME=/datachile
      - VIRTUAL_HOST=datachile.io,en.datachile.io,es.datachile.io,www.datachile.io
      - LETSENCRYPT_HOST=datachile.io,en.datachile.io,es.datachile.io,www.datachile.io
      - LETSENCRYPT_EMAIL=datachile@datawheel.us
    volumes:
      - canon-static:/datachile/static-shared
    depends_on:
      - datachile-mondrian
    links:
      - datachile-mondrian

  nginx:
    image: nginx
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - canon-static:/datachile-files:ro
      - /home/manuel/mondrian-rest-ui/build/:/mondrian-rest-ui-files
      - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d
      - ./dockerfiles/nginx/vhost.d:/etc/nginx/vhost.d
      - ./dockerfiles/nginx/html:/usr/share/nginx/html
      - ./dockerfiles/nginx/certs:/etc/nginx/certs:ro
      - ./dockerfiles/datachile-htpasswd:/etc/nginx/htpasswd:ro
    tmpfs: /nginx-cache:exec,mode=1777

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - ./dockerfiles/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d
      - ./dockerfiles/nginx/vhost.d:/etc/nginx/vhost.d
      - ./dockerfiles/nginx/html:/usr/share/nginx/html
      - ./dockerfiles/nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro


  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d
      - ./dockerfiles/nginx/vhost.d:/etc/nginx/vhost.d
      - ./dockerfiles/nginx/html:/usr/share/nginx/html
      - ./dockerfiles/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"

volumes:
  db-data:
    driver: local-persist
    driver_opts:
      mountpoint: /data/postgres
  canon-static:
    
